// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestContainers.ApiApp.Infrastructure;

#nullable disable

namespace TestContainers.ApiApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240523215111_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestContainers.ApiApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Department 1",
                            Email = "employee1@test.com",
                            Name = "Employee 1",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Department 2",
                            Email = "employee2@test.com",
                            Name = "Employee 2",
                            Phone = "1234567891"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Department 3",
                            Email = "employee3@test.com",
                            Name = "Employee 3",
                            Phone = "1234567892"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Department 4",
                            Email = "employee4@test.com",
                            Name = "Employee 4",
                            Phone = "1234567893"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Department 5",
                            Email = "employee5@test.com",
                            Name = "Employee 5",
                            Phone = "1234567894"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
